#!/bin/sh

root="$HOME/dev/spmk/root"
pkgdb="$root/var/lib/spmk

die() {
	echo error: "$1" >&2
	exit 1
}

current_version() {
  for f in "$pkgdb/$1"-[0-9]*; do
    basename "$f"
    break
  done
}

remove_files() {
  tac "$1" | while read -r f ; do
    if test -f "$root/$f"; then
      rm -f "$root/$f"
    elif test -d "$root/$f"; then
      rmdir "$root/$f" 2>/dev/null || true
    fi
  done
}

pkg="$1"
test -d "$pkgdb/$pkg" || pkg=$(current_version "$1")
test -d "$pkgdb/$pkg" || die "Cannot find package '$1'."

if test -f "$pkgdb/$pkg/uninstall" ; then
  sh -c ". '$tmp/+PKG/uninstall'" || die 'Error in uninstall script.'
fi

remove_files "$pkgdb/$pkg/files"
rm -rf "$pkgdb/$pkg"
