#!/bin/sh

root="${SPMK_ROOT:-$HOME/dev/spmk/root}"
pkgdb="${SPMK_DB:-$root/var/lib/spmk}"
save="$root/etc/spmk/save"

die() {
  echo error: "$1" >&2
  exit 1
}

current_version() {
  for f in "$pkgdb"/"$1"-[0-9]*; do
    basename "$f"
    break
  done
}

remove_files() {
  awk <"$1" '{print NR " " $0}' | sort -r -n | sed 's/^[0-9]* //' \
  | while IFS='' read -r f ; do
    if test -f "$save" && echo "$f" | grep -f "$save" >/dev/null; then
      mv "$root/$f" "$root/$f.saved"
    elif test -f "$root/$f"; then
      rm -f "$root/$f"
    elif test -d "$root/$f"; then
      rmdir "$root/$f" 2>/dev/null || true
    fi
  done
}

remove() {
  pkg="$1"
  test -d "$pkgdb/$pkg" || pkg="$(current_version "$1")"
  test -d "$pkgdb/$pkg" || die "Cannot find package '$1'."

  if test -f "$pkgdb/$pkg/uninstall" ; then
    sh -c ". '$tmp/+PKG/uninstall'" || die 'Error in uninstall script.'
  fi

  remove_files "$pkgdb/$pkg/files"
  rm -rf "$pkgdb/$pkg"
}

for a; do remove "$a"; done
