.TH SPKG 1
.SH NAME
spmk \- port/package utility
.SH SYNOPSIS
.B spmk
.RB [ -b
|
.B -a
|
.B -r
|
.B -d
|
.BR -rd ]
.I [packages]
.I ...
.SH DESCRIPTION
.I Spkg
is a port management utility that tracks installed packages on *nix system.
It features dependency support. If no arguments provided it tries to build
package from
.I build.mk
in current directory if there is one.
.SH OPERATIONS
.TP
.B -b
Builds packages.
.TP
.B -a
Add packages.
.I Not implemented yet.
.TP
.B -r
Remove packages.
.TP
.B -d
List package dependencies.
.TP
.B -rd
List all installed packages that are required by packages supplied in
arguments.
.TP
.B -u
Update all packages.
.I Not implemented yet.
