.Dd Nov 25, 2012
.Dt SPMK 1 1
.Os
.Sh NAME

.Nm spmk
.Nd port/package utility

.Sh SYNOPSIS
.Nm
.Op Fl b
.Op Fl a
.Op Fl r
.Op Fl d
.Op Fl rd
.Ar package
.Bk -words
.Op Ar packages ...
.Ek

.Sh DESCRIPTION
.Nm
is a port management utility that tracks installed packages on *nix system.
It features dependency support. If no arguments provided it tries to build
package from
.Pa build.mk
in current directory if there is one.

See
.Pa sample/build.mk
as an example of writing spmk
.Pa build.mk
files.

.Sh OPERATIONS
.Bl -tag
.It Ar -b
Builds packages.
.It Ar -r
Removes packages.
.It Ar -d
List package dependencies.
.It Ar -rd
List all installed packages that are required by packages supplied in
arguments.
.It Ar -u
Update all packages.
.Aq Not implemented yet.
