#!/bin/sh

root="$HOME/dev/spmk/root"
pkgdb="$root/var/lib/spmk"
tmpdir="$root/tmp/spmk"
pubkeydir="$root/keys"
exclude="$root/etc/spmk/exclude"
noverify=
reason='explicit'

while test $# -gt 0; do
  case "$1" in
    -n) noverify='yes'; shift;;
    -f) force='yes'; shift;;
    -d) reason='dependency'; shift;;
    -*) echo 'usage: spmk_add [-n] [-f] [-d] pkg...' >&2; exit 1;;
    *) break;;
  esac
done

die() {
  echo error: "$1" >&2
  exit 1
}

verify() {
  for k in "$pubkeydir"/*; do
    if openssl dgst -sha1 -verify "$k" -signature "$2" <"$1" >/dev/null; then
      return
    fi
  done
  false
}

current_version() {
  for f in "$pkgdb/$1"-[0-9]*; do
    basename "$f"
    break
  done
}

remove_files() {
  awk < "$1" '{print NR " " $0;}' | sort -r -n | sed 's/^[0-9]* //' \
  | while IFS='' read -r f ; do
    if test -f "$root/$f"; then
      rm -f "$root/$f"
    elif test -d "$root/$f"; then
      rmdir "$root/$f" 2>/dev/null || true
    fi
  done
}

add() {
  pkgfile="$1"
  pkg=$(basename "$pkgfile" | sed 's/-[^-]*$//')
  pkgname=$(echo "$pkg" | sed 's/-[0-9].*$//')
  tmp="$tmpdir/$pkg"

  if test -z "$noverify" ; then
    test -f "$pkgfile.sig" || die "Package '$pkgfile' not signed."
    verify "$pkgfile" "$pkgfile.sig" || die "Package '$pkgfile' is corrupted."
  fi

  rm -rf "$tmp"
  mkdir -p "$tmp" || die "Cannot create temp directory '$tmp'"
  excl="$tmpdir/exclude"
  echo '+PKG' > "$excl"
  test -f "$exclude" && cat "$exclude" >> "$excl"
  trap "rm -rf '$excl' '$tmp'" EXIT

  gunzip < "$pkgfile" | (cd "$tmp"; tar -x -f - "+PKG") \
  || die "Broken package."
  gunzip < "$pkgfile" | tar -t -f - -X "$excl" | grep -v '^+PKG' \
  > $tmp/files || die "Broken package."

  cur=$(current_version "$pkgname")

  if test -n "$cur" && test -e "$pkgdb/$cur"; then
    test -f "$pkgdb/$pkg/uninstall" && sh -c ". '$pkgdb/$pkg/uninstall'"
    remove_files "$pkgdb/$cur/files"
    rm -rf "$pkgdb/$cur"
  fi

  if test -z "$force"; then
    while IFS='' read -r f ; do
      case "$f" in
        */) check='-f' ;;
        *) check='-e' ;;
      esac
      if test $check "$root/$f"; then
        echo "error: File '$root/$f' already exists." >&2
        s=error
      fi
    done < "$tmp/files"
    test "$s" = error && die 'Aborting install.'
  fi

  if ! gunzip < "$pkgfile" | (cd "$root" && tar -x -f - -X "$excl") ; then
    remove_files "$tmp/files"
    die "Couldn't unpack contents of '$pkgfile'"
  fi

  if test -z "$spmk_no_installscript" && test -f "$tmp/+PKG/install" ; then
    sh -c ". '$tmp/+PKG/install'" || {
      remove_files "$tmp/files"
      die 'Error in install script.'
    }
  fi

  mkdir -p "$pkgdb/$pkg"
  echo "reason: $reason" >> "$tmp/+PKG/info"
  gunzip < "$pkgfile" | tar -t -f - | grep -v '^+PKG' > "$pkgdb/$pkg/files"
  cp "$tmp/+PKG"/* "$pkgdb/$pkg"
  rm -rf "$excl" "$tmp"
}

for a; do add "$a"; done
trap '' EXIT
